language: dart
branches:
  only:
  - master
  # Semantic version tags and legacy branches of the form "1.2.x".
  - "/^\\d+\\.\\d+\\.(\\d+([+-].*)?|x)$/"

cache:
  directories:
  - $HOME/.pub-cache

env:
  global:
  - PROTOBUF_VERSION=3.10.1
  - PATH="$HOME/protoc/bin:$PATH"

before_install:
- if [[ "$TRAVIS_OS_NAME" = windows ]]; then
    curl -Lo protoc.zip https://github.com/protocolbuffers/protobuf/releases/download/v${PROTOBUF_VERSION}/protoc-${PROTOBUF_VERSION}-win64.zip;
  else
    curl -Lo protoc.zip https://github.com/protocolbuffers/protobuf/releases/download/v${PROTOBUF_VERSION}/protoc-${PROTOBUF_VERSION}-${TRAVIS_OS_NAME}-x86_64.zip;
  fi
- unzip -d "$HOME/protoc" protoc.zip

before_script:
- pub run grinder protobuf
# Format the generated code or else the formatter task will get upset.
- dartfmt -w --fix lib/src/embedded_sass.pb*

# TODO(nweiz): always compile native when we're running on Dart 2.7.
- if [[ "$TRAVIS_OS_NAME" = windows ]]; then
    pub run grinder pkg-compile-snapshot;
  else
    pub run grinder pkg-compile-native;
  fi

jobs:
  include:

  # Testing
  - dart: stable
    dart_task: test
  - dart: dev
    dart_task: test
  - dart: stable
    os: windows
    dart_task: test
  - dart: stable
    os: osx
    dart_task: test

  # Static checks
  - dart_task: {dartanalyzer: --fatal-warnings ./}
  - dart_task: dartfmt
