name: sass_embedded
version: 1.0.0-dev
description: An implementation of the Sass embedded protocol using Dart Sass.
author: Sass Team
homepage: https://github.com/sass/dart-sass-embedded

environment:
  sdk: '>=2.4.0 <3.0.0'

executables:
  dart-sass-embedded: dart_sass_embedded

dependencies:
  async: ">=1.13.0 <3.0.0"
  meta: ^1.1.0
  protobuf: ^1.0.0
  sass: ^1.21.0
  source_maps: ^0.10.5
  source_span: ^1.1.0
  stack_trace: ^1.6.0
  stream_channel: ">=1.6.0 <3.0.0"
  typed_data: ^1.1.0

dev_dependencies:
  cli_pkg: ^1.0.0-beta.8
  grinder: ^0.8.0
  protoc_plugin: ^19.0.0
  path: ^1.6.0
  test: ^1.0.0
  test_descriptor: ^1.0.0
