name: sass_embedded
version: 1.0.0-beta.14
description: An implementation of the Sass embedded protocol using Dart Sass.
homepage: https://github.com/sass/dart-sass-embedded

environment:
  sdk: '>=2.12.0 <3.0.0'

executables:
  dart-sass-embedded: dart_sass_embedded

dependencies:
  async: ">=1.13.0 <3.0.0"
  meta: ^1.1.0
  protobuf: ^2.0.0
  sass: ^1.42.0
  sass_api: ^1.0.0-beta.5
  source_span: ^1.1.0
  stack_trace: ^1.6.0
  stream_channel: ">=1.6.0 <3.0.0"
  typed_data: ^1.1.0

dev_dependencies:
  cli_pkg: ^1.4.0
  grinder: ^0.9.0
  protoc_plugin: ^20.0.0
  path: ^1.6.0
  test: ^1.0.0
  test_descriptor: ^2.0.0
  yaml: ^3.1.0
  pubspec_parse: ^1.0.0
  pub_semver: ^2.0.0
