name: CI

env:
  protoc_version: '3.x'

on:
  push:
    branches: [main, feature.*]
    tags: ['**']
  pull_request:

jobs:
  dart_tests:
    name: "Dart tests | Dart ${{ matrix.dart_channel }} | ${{ matrix.os }}"
    runs-on: "${{ matrix.os }}"

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        dart_channel: [stable]
        include: [{os: ubuntu-latest, dart_channel: dev}]

    steps:
      - uses: actions/checkout@v3
      - uses: arduino/setup-protoc@v1
        with: { version: "${{ env.protoc_version }}", repo-token: "${{ github.token }}" }
      - uses: dart-lang/setup-dart@v1
        with: {sdk: "${{ matrix.dart_channel }}"}

      - name: Check out Dart Sass only if linked in the PR description
        uses: sass/clone-linked-repo@v1
        with:
          repo: sass/dart-sass
          path: build/dart-sass
          default-ref: null

      - name: Check out Dart Sass from main HEAD when using -dev dependency
        run: |
          if [[ ! -d build/dart-sass ]] && grep --quiet -E '\bsass:\s*.*-dev["'"'"']?$' pubspec.yaml; then
            git clone https://github.com/sass/dart-sass.git \
              --depth 1 build/dart-sass
          fi
        shell: bash

      - name: Override dart-sass dependency only if repo was cloned a priori
        run: |
          if [[ -d build/dart-sass ]]; then
            (
              echo "dependency_overrides:"
              echo "  sass: {path: build/dart-sass}"
              echo "  sass_api: {path: build/dart-sass/pkg/sass_api}"
            ) >> pubspec.yaml
          fi
        shell: bash

      - name: Check out embedded Sass protocol
        uses: sass/clone-linked-repo@v1
        with: {repo: sass/embedded-protocol, path: build/embedded-protocol}

      - run: dart pub get
      - run: dart run grinder protobuf
        env: {UPDATE_SASS_PROTOCOL: false}
      - run: dart run grinder pkg-standalone-dev
      - name: Run tests
        run: dart run test -r expanded

  # The versions should be kept up-to-date with the latest LTS Node releases.
  # They next need to be rotated October 2021. See
  # https://github.com/nodejs/Release.
  sass_spec:
    name: 'JS API Tests | Node ${{ matrix.node_version }} | ${{ matrix.os }}'
    runs-on: ${{ matrix.os }}-latest

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu, windows, macos]
        node_version: [16]
        include:
          # Include LTS versions on Ubuntu
          - os: ubuntu
            node_version: 14
          - os: ubuntu
            node_version: 12

    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1
        with: {sdk: stable}
      - uses: arduino/setup-protoc@v1
        with:
          version: ${{ env.PROTOC_VERSION }}
          repo-token: '${{ github.token }}'

      - name: Check out Dart Sass only if linked in the PR description
        uses: sass/clone-linked-repo@v1
        with:
          repo: sass/dart-sass
          path: build/dart-sass
          default-ref: null

      - name: Check out Dart Sass from main HEAD when using -dev dependency
        run: |
          if [[ ! -d build/dart-sass ]] && grep --quiet -E '\bsass:\s*.*-dev["'"'"']?$' pubspec.yaml; then
            git clone https://github.com/sass/dart-sass.git \
              --depth 1 build/dart-sass
          fi
        shell: bash

      - name: Override dart-sass dependency only if repo was cloned a priori
        run: |
          if [[ -d build/dart-sass ]]; then
            (
              echo "dependency_overrides:"
              echo "  sass: {path: build/dart-sass}"
              echo "  sass_api: {path: build/dart-sass/pkg/sass_api}"
            ) >> pubspec.yaml
          fi
        shell: bash

      - name: Check out embedded Sass protocol
        uses: sass/clone-linked-repo@v1
        with: {repo: sass/embedded-protocol, path: build/embedded-protocol}

      - name: Check out the embedded host
        uses: sass/clone-linked-repo@v1
        with: {repo: sass/embedded-host-node}

      - name: Check out the JS API definition
        uses: sass/clone-linked-repo@v1
        with: {repo: sass/sass, path: language}

      - name: "Embedded host: npm install"
        run: npm install
        working-directory: embedded-host-node
      - name: "Embedded host: npm run init"
        run: |
          npm run init -- --protocol-path=../build/embedded-protocol --compiler-path=.. --api-path=../language
        working-directory: embedded-host-node

      - name: Check out sass-spec
        uses: sass/clone-linked-repo@v1
        with: {repo: sass/sass-spec}

      - name: Install sass-spec dependencies
        run: npm install
        working-directory: sass-spec

      - name: Compile embedded host
        run: |
          npm run compile
          mv {`pwd`/,dist/}lib/src/vendor/dart-sass-embedded
        shell: bash
        working-directory: embedded-host-node

      - name: Run tests
        run: npm run js-api-spec -- --sassPackage ../embedded-host-node --sassSassRepo ../language
        working-directory: sass-spec

  static_analysis:
    name: Static analysis
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: arduino/setup-protoc@v1
        with: { version: "${{ env.protoc_version }}", repo-token: "${{ github.token }}" }
      - uses: dart-lang/setup-dart@v1

      - name: Check out Dart Sass only if linked in the PR description
        uses: sass/clone-linked-repo@v1
        with:
          repo: sass/dart-sass
          path: build/dart-sass
          default-ref: null

      - name: Check out Dart Sass from main HEAD when using -dev dependency
        run: |
          if [[ ! -d build/dart-sass ]] && grep --quiet -E '\bsass:\s*.*-dev["'"'"']?$' pubspec.yaml; then
            git clone https://github.com/sass/dart-sass.git \
              --depth 1 build/dart-sass
          fi
        shell: bash

      - name: Override dart-sass dependency only if repo was cloned a priori
        run: |
          if [[ -d build/dart-sass ]]; then
            (
              echo "dependency_overrides:"
              echo "  sass: {path: build/dart-sass}"
              echo "  sass_api: {path: build/dart-sass/pkg/sass_api}"
            ) >> pubspec.yaml
          fi
        shell: bash

      - name: Check out embedded Sass protocol
        uses: sass/clone-linked-repo@v1
        with: {repo: sass/embedded-protocol, path: build/embedded-protocol}

      - run: dart pub get
      - run: dart run grinder protobuf
        env: {UPDATE_SASS_PROTOCOL: false}
      - name: Analyze dart
        run: dart analyze --fatal-warnings ./

  format:
    name: Code formatting
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: dart-lang/setup-dart@v1
    - run: dart format --fix .
    - run: git diff --exit-code

  deploy_github_linux:
    name: "Deploy Github: linux-ia32, linux-x64"
    runs-on: ubuntu-latest
    needs: [dart_tests, sass_spec, static_analysis, format]
    if: "startsWith(github.ref, 'refs/tags/') && github.repository == 'sass/dart-sass-embedded'"

    steps:
      - uses: actions/checkout@v3
      - uses: arduino/setup-protoc@v1
        with: { version: "${{ env.protoc_version }}", repo-token: "${{ github.token }}" }
      - uses: dart-lang/setup-dart@v1
      - run: dart pub get
      - run: dart run grinder protobuf
      # We need to upload the compiled protobuf rather than recompiling it on
      # other platforms because arduino/setup-protoc currently) requires Node 12
      # which doesn't support ARM.
      - uses: actions/upload-artifact@v3
        with:
          name: embedded-protocol
          path: |
            build/embedded-protocol
            lib/src/embedded_sass.*.dart
      - name: Deploy
        run: dart run grinder pkg-github-release pkg-github-linux-ia32 pkg-github-linux-x64
        env: {GH_BEARER_TOKEN: "${{ github.token }}"}

  deploy_github_linux_qemu:
    name: "Deploy Github: linux-${{ matrix.arch }}"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          # https://github.com/dart-lang/sdk/pull/48665
          # - arch: arm
          #   platform: linux/arm/v7
          - arch: arm64
            platform: linux/arm64
    needs: [deploy_github_linux]
    if: "startsWith(github.ref, 'refs/tags/') && github.repository == 'sass/dart-sass-embedded'"

    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: embedded-protocol
      - uses: docker/setup-qemu-action@v2
      - name: Deploy
        run: |
          docker run --rm \
            --env "GH_BEARER_TOKEN=$GH_BEARER_TOKEN" \
            --platform ${{ matrix.platform }} \
            --volume "$PWD:$PWD" \
            --workdir "$PWD" \
            docker.io/library/dart:latest \
            /bin/sh -c "dart pub get && dart run grinder pkg-github-linux-${{ matrix.arch }}"
        env: {GH_BEARER_TOKEN: "${{ github.token }}"}

  deploy_github:
    name: "Deploy Github: ${{ matrix.platform }}"
    runs-on: ${{ matrix.runner }}
    needs: [deploy_github_linux]
    if: "startsWith(github.ref, 'refs/tags/') && github.repository == 'sass/dart-sass-embedded'"
    strategy:
      matrix:
        include:
          - runner: macos-latest
            platform: macos-x64
            architecture: x64
          - runner: self-hosted
            platform: macos-arm64
            architecture: arm64
          - runner: windows-latest
            platform: windows
            architecture: x64

    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: embedded-protocol
      - uses: dart-lang/setup-dart@v1
        # Workaround for dart-lang/setup-dart#59
        with:
          architecture: ${{ matrix.architecture }}
      - run: dart pub get
      - name: Deploy
        run: dart run grinder pkg-github-${{ matrix.platform }}
        env: {GH_BEARER_TOKEN: "${{ github.token }}"}

  release_embedded_host:
    name: "Release Embedded Host"
    runs-on: ubuntu-latest
    needs: [deploy_github_linux, deploy_github_linux_qemu, deploy_github]
    if: "startsWith(github.ref, 'refs/tags/') && github.repository == 'sass/dart-sass-embedded'"

    steps:
      - uses: actions/checkout@v3
        with:
          repository: sass/embedded-host-node
          token: ${{ secrets.GH_TOKEN }}

      - name: Get version
        id: version
        run: echo "::set-output name=version::${GITHUB_REF##*/}"

      - name: Update version
        run: |
          # Update binary package versions
          for dir in $(ls npm); do
            cat "npm/$dir/package.json" |
                jq --arg version ${{ steps.version.outputs.version }} '
                  .version |= $version
                ' > package.json.tmp &&
              mv package.json.tmp "npm/$dir/package.json"
          done

          # Update main package version and dependencies on binary packages
          cat package.json |
              jq --arg version ${{ steps.version.outputs.version }} '
                .version |= $version |
                ."compiler-version" |= $version |
                .optionalDependencies = (.optionalDependencies | .[] |= $version)
              ' > package.json.tmp &&
            mv package.json.tmp package.json
          curl https://raw.githubusercontent.com/sass/dart-sass/${{ steps.version.outputs.version }}/CHANGELOG.md > CHANGELOG.md
        shell: bash

      - uses: EndBug/add-and-commit@v8
        with:
          author_name: Sass Bot
          author_email: sass.bot.beep.boop@gmail.com
          message: Update compiler version and release
          tag: ${{ steps.version.outputs.version }}
